// <auto-generated />
using System;
using CsvTest.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CsvTest.Infrastructure.Migrations
{
    [DbContext(typeof(CsvTestContext))]
    [Migration("20241218095917_CsvDataInit")]
    partial class CsvDataInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CsvTest.Infrastructure.Database.Data.CsvData", b =>
                {
                    b.Property<int>("CsvDataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CsvDataID"));

                    b.Property<int>("DOLocationID")
                        .HasColumnType("int");

                    b.Property<decimal>("FareAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PULocationID")
                        .HasColumnType("int");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<string>("StoreFwdFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TpepDropOffDatetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TpepPickupDatetime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TripDistance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CsvDataID");

                    b.ToTable("CsvDatas");
                });

            modelBuilder.Entity("CsvTest.Infrastructure.Database.Data.CsvDataWithJson", b =>
                {
                    b.Property<int>("CsvDataWithJsonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CsvDataWithJsonID"));

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CsvDataWithJsonID");

                    b.ToTable("CsvDatasJson");
                });
#pragma warning restore 612, 618
        }
    }
}
